<a href="https://colab.research.google.com/github/ebolofis/Data-Science-Machine-Learning/blob/main/CAM_DS__C201_Activity_2_3_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**First things first** - please go to 'File' and select 'Save a copy in Drive' so that you have your own version of this activity set up and ready to use.
Remember to update the portfolio index link to your own work once completed!

# Activity 2.3.4: Performing manual propagation

## Scenario
A tech startup developing a recommendation engine for online retail needs its neural network created and optimised for maximum accuracy and efficiency. As a data scientist, you’ve been tasked with creating the network, initialising weights and biases, defining input variables, selecting activation functions, computing gradients, and using gradient descent to fine-tune the model. The end result will be a model with improved recommendation accuracy that drives customer engagement in the online retail sector.

## Objective
Manually complete a forward and backward pass in a neural network.

You’ll complete the activity in your Notebook, where you’ll:
- create a simple neural network
- initialise weights and biases
- provide input variables
- define activation functions and their derivatives
- compute hidden-layer gradients
- use gradient descent to optimise weights and biases.

## Assessment criteria
By completing this activity, you'll be able to provide evidence that you can create a simple neural network and complete a forward and backward pass.

## Activity guidance
1. Import the relevant libraries.
2. Create a neural network with an input dimension of 2, one hidden layer, and one output layer.
  - For the hidden layer, initialise the weights as a 2x2 matrix, where the rows and columns of the matrix are np.array([0.2, 0.9], [0.6, 0.6]).
  - For the hidden layer, initialise the bias vectors as np.array([0.8, 0.9]).
  - For the output layer, initialise the weights as a 1x2 matrix, with weights np.array([[0.9], [0.4]]).
  - For the output layer, initialise the bias neuron as np.array([0.9]).
3. Define the input data as the variable X made of two elements: 0.3 and 0.4.
4. Define the ReLu function.
5. Print the input data, hidden layer output, and final output.
6. Define the ReLu and Sigmoid functions and also their derivatives.
7. Assume the target for binary classification is 1 and save it in a variable called target.
8. Compute the loss derivative with respect to the final output.
9. Complete a backward pass through the output layer.
10. Compute the gradients for the output layer parameters.
11. Complete a backward pass through the hidden layer.
12. Compute the gradients for the hidden layer parameters.
13. Set a simple learning rate of 0.02.
14. Update the weights and biases using gradient descent.
15. Print the updated weights and biases.

In [4]:
import numpy as np

# --- 1. Import relevant libraries (NumPy already imported) ---
# (Step 1 of activity guidance)

# --- 2. Create a neural network and initialise weights and biases ---
# (Step 2 of activity guidance)

# Input dimension is 2, one hidden layer, and one output layer.

# Hidden layer parameters
# Weights as a 2x2 matrix
W_h = np.array([[0.2, 0.9], [0.6, 0.6]])
# Bias vector
b_h = np.array([0.8, 0.9])

# Output layer parameters
# Weights as a 2x1 matrix (as np.array([[0.9], [0.4]]) is 2x1)
W_o = np.array([[0.9], [0.4]])
# Bias neuron
b_o = np.array([0.9])

# --- 3. Define the input data ---
# (Step 3 of activity guidance)
# X made of two elements: 0.3 and 0.4
X = np.array([0.3, 0.4])

# --- 4. Define the ReLu function (used in forward pass) ---
# (Step 4 of activity guidance, also part of step 6)
def relu(x):
    """Applies the Rectified Linear Unit (ReLU) activation function element-wise."""
    return np.maximum(0, x)

# --- Forward Pass ---

# Calculate Hidden Layer's Weighted Input (z_h) and Activation (a_h)
# z_h = X . W_h + b_h
z_h = np.dot(X, W_h) + b_h
# a_h = relu(z_h)
a_h = relu(z_h)

# --- 6. Define the Sigmoid function (used in forward pass) and derivatives ---
# (Step 6 of activity guidance)
def sigmoid(x):
    """Applies the Sigmoid activation function element-wise."""
    return 1 / (1 + np.exp(-x))

# Calculate Output Layer's Weighted Input (z_o) and Final Output (final_output)
# z_o = a_h . W_o + b_o
z_o = np.dot(a_h, W_o) + b_o
# final_output = sigmoid(z_o)
final_output = sigmoid(z_o)

# --- 5. Print the input data, hidden layer output, and final output ---
# (Step 5 of activity guidance)
print("--- Forward Pass Outputs ---")
print(f"Input Data (X):\n{X}")
print(f"Shape of X: {X.shape}\n")

print(f"Hidden Layer Weights (W_h):\n{W_h}")
print(f"Shape of W_h: {W_h.shape}")
print(f"Hidden Layer Biases (b_h):\n{b_h}")
print(f"Shape of b_h: {b_h.shape}\n")

print(f"Weighted input to Hidden Layer (z_h):\n{z_h}")
print(f"Shape of z_h: {z_h.shape}")
print(f"Activation of Hidden Layer (a_h):\n{a_h}")
print(f"Shape of a_h: {a_h.shape}\n")

print(f"Output Layer Weights (W_o):\n{W_o}")
print(f"Shape of W_o: {W_o.shape}")
print(f"Output Layer Bias (b_o):\n{b_o}")
print(f"Shape of b_o: {b_o.shape}\n")

print(f"Weighted input to Output Layer (z_o):\n{z_o}")
print(f"Shape of z_o: {z_o.shape}")
print(f"Final Output of the Network (final_output):\n{final_output}")
print(f"Shape of final_output: {final_output.shape}\n")

# Define derivatives of activation functions (ReLU and Sigmoid)
# (Step 6 of activity guidance - continued)
def relu_derivative(x):
    """Computes the derivative of the ReLU function."""
    # Returns 1 if x > 0, else 0
    return np.where(x > 0, 1, 0)

def sigmoid_derivative(sigmoid_output):
    """
    Computes the derivative of the Sigmoid function.
    Takes the output of the sigmoid function as input.
    """
    # Derivative is sigmoid(x) * (1 - sigmoid(x))
    return sigmoid_output * (1 - sigmoid_output)

# --- Backward Pass ---

# --- 7. Assume the target for binary classification is 1 ---
# (Step 7 of activity guidance)
target = 1.0

# --- 8. Compute the loss derivative with respect to the final output ---
# (Step 8 of activity guidance)
# Using Mean Squared Error derivative: (final_output - target)
d_loss_d_final_output = final_output - target

# --- 9. Complete a backward pass through the output layer ---
# (Step 9 of activity guidance)
# This involves calculating the error term (delta) for the output layer.

# Derivative of the final output with respect to the output layer's weighted input (z_o)
# This is the derivative of the sigmoid function evaluated at z_o, using final_output.
d_final_output_d_z_o = sigmoid_derivative(final_output)

# Error term for the output layer (delta_o)
# delta_o = dL/dfinal_output * dfinal_output/dz_o
delta_o = d_loss_d_final_output * d_final_output_d_z_o

# --- 10. Compute the gradients for the output layer parameters ---
# (Step 10 of activity guidance)

# Gradient for Output Layer Weights (W_o)
# dL/dW_o = dL/dz_o * dz_o/dW_o = delta_o * a_h
# a_h needs to be reshaped to a column vector for this multiplication if delta_o is scalar.
# W_o is (2,1), a_h is (2,), delta_o is scalar-like.
d_loss_d_W_o = a_h.reshape(-1, 1) * delta_o

# Gradient for Output Layer Bias (b_o)
# dL/db_o = dL/dz_o * dz_o/db_o = delta_o * 1
d_loss_d_b_o = delta_o

# --- Print Gradients for Output Layer ---
print("--- Backward Pass: Output Layer Gradients ---")
print(f"Target: {target}")
print(f"Loss derivative w.r.t. final_output (d_loss_d_final_output): {d_loss_d_final_output}")
print(f"Sigmoid derivative of final_output w.r.t. z_o (d_final_output_d_z_o): {d_final_output_d_z_o}")
print(f"Error term for output layer (delta_o): {delta_o}")
print(f"Gradient for W_o (d_loss_d_W_o):\n{d_loss_d_W_o}")
print(f"Shape of d_loss_d_W_o: {d_loss_d_W_o.shape}")
print(f"Gradient for b_o (d_loss_d_b_o): {d_loss_d_b_o}")
if hasattr(d_loss_d_b_o, 'shape'):
    print(f"Shape of d_loss_d_b_o: {d_loss_d_b_o.shape}")

    # (Continuing from the previous block in the same cell)

# --- 11. Complete a backward pass through the hidden layer ---
# (Step 11 of activity guidance)
# This involves propagating the error from the output layer back to the hidden layer.

# Derivative of the loss with respect to the hidden layer's activation (a_h)
# dL/da_h = dL/dz_o * dz_o/da_h
# dL/dz_o is delta_o (error term from output layer)
# dz_o/da_h is W_o.T (transpose of output layer weights)
# So, d_loss_d_a_h = np.dot(delta_o, W_o.T)
# However, given shapes: delta_o is (1,), W_o is (2,1), W_o.T is (1,2).
# The error propagated back to a_h neurons is sum_k(delta_ok * W_okj)
# For a single output neuron, delta_o is scalar-like.
# d_loss_d_a_h_j = delta_o * W_oj (where W_oj is the weight from hidden_j to output_0)
# This means we need to multiply delta_o by each column of W_o (or row of W_o.T)
# d_loss_d_a_h will be shaped like a_h (2,).
# Correct formulation: The gradient passed back from z_o to a_h is delta_o . W_o^T
# np.dot(W_o, delta_o) gives shape (2,). Taking .T doesn't change it. This is dL/da_h.
d_loss_d_a_h = np.dot(W_o, delta_o).flatten() # ensures it's a 1D array like a_h

# Derivative of the hidden layer's activation (a_h) with respect to its weighted input (z_h)
# This is the derivative of the ReLU function applied to z_h.
d_a_h_d_z_h = relu_derivative(z_h)

# Error term for the hidden layer (delta_h)
# delta_h = dL/da_h * da_h/dz_h (element-wise)
delta_h = d_loss_d_a_h * d_a_h_d_z_h

# --- 12. Compute the gradients for the hidden layer parameters ---
# (Step 12 of activity guidance)

# Gradient for Hidden Layer Weights (W_h)
# dL/dW_h = dL/dz_h * dz_h/dW_h
# dL/dz_h is delta_h
# dz_h/dW_h is X (input vector)
# So, dL/dW_h = X.T * delta_h (outer product if X is row and delta_h is row)
# X is (2,), delta_h is (2,). W_h is (2,2).
# We need an outer product: np.outer(X, delta_h)
d_loss_d_W_h = np.outer(X, delta_h)

# Gradient for Hidden Layer Bias (b_h)
# dL/db_h = dL/dz_h * dz_h/db_h
# dz_h/db_h is 1
# So, dL/db_h = delta_h
d_loss_d_b_h = delta_h

# --- Print Gradients for Hidden Layer ---
print("\n--- Backward Pass: Hidden Layer Gradients ---")
print(f"Derivative of loss w.r.t. hidden activation a_h (d_loss_d_a_h):\n{d_loss_d_a_h}")
print(f"Shape of d_loss_d_a_h: {d_loss_d_a_h.shape}")
print(f"Derivative of hidden activation a_h w.r.t. z_h (d_a_h_d_z_h):\n{d_a_h_d_z_h}")
print(f"Shape of d_a_h_d_z_h: {d_a_h_d_z_h.shape}")
print(f"Error term for hidden layer (delta_h):\n{delta_h}")
print(f"Shape of delta_h: {delta_h.shape}")
print(f"Gradient for W_h (d_loss_d_W_h):\n{d_loss_d_W_h}")
print(f"Shape of d_loss_d_W_h: {d_loss_d_W_h.shape}")
print(f"Gradient for b_h (d_loss_d_b_h):\n{d_loss_d_b_h}")
print(f"Shape of d_loss_d_b_h: {d_loss_d_b_h.shape}")


--- Forward Pass Outputs ---
Input Data (X):
[0.3 0.4]
Shape of X: (2,)

Hidden Layer Weights (W_h):
[[0.2 0.9]
 [0.6 0.6]]
Shape of W_h: (2, 2)
Hidden Layer Biases (b_h):
[0.8 0.9]
Shape of b_h: (2,)

Weighted input to Hidden Layer (z_h):
[1.1  1.41]
Shape of z_h: (2,)
Activation of Hidden Layer (a_h):
[1.1  1.41]
Shape of a_h: (2,)

Output Layer Weights (W_o):
[[0.9]
 [0.4]]
Shape of W_o: (2, 1)
Output Layer Bias (b_o):
[0.9]
Shape of b_o: (1,)

Weighted input to Output Layer (z_o):
[2.454]
Shape of z_o: (1,)
Final Output of the Network (final_output):
[0.92085347]
Shape of final_output: (1,)

--- Backward Pass: Output Layer Gradients ---
Target: 1.0
Loss derivative w.r.t. final_output (d_loss_d_final_output): [-0.07914653]
Sigmoid derivative of final_output w.r.t. z_o (d_final_output_d_z_o): [0.07288236]
Error term for output layer (delta_o): [-0.00576839]
Gradient for W_o (d_loss_d_W_o):
[[-0.00634522]
 [-0.00813342]]
Shape of d_loss_d_W_o: (2, 1)
Gradient for b_o (d_loss_d_b_o): [

> Start your activity here. Select the pen from the toolbar to add your entry.

# Reflect

Write a brief paragraph highlighting your process and rationale to showcase critical thinking and problem-solving.

> Select the pen from the toolbar to add your entry. When you’ve completed the activity, remember to update the link on your contents page to point to your completed Notebook.